# Selective column configuration for Embryoscope Gold Layer
# Maps specific source columns to the final gold table

# Patient columns
patients:
  - prontuario   # Key for joining with Clinisys
  - PatientID
  - PatientIDx
  - FirstName
  - LastName
  - DateOfBirth
  - YearOfBirth  # Calculated feature
  - unit_huntington
# Treatment columns
treatments:
  - TreatmentName

# Embryo columns
embryo_data:
  # Standard columns
  - EmbryoID
  - EmbryoDate   # Calculated feature
  - embryo_number
  - Position
  - InstrumentNumber
  - WellNumber
  - FertilizationTime
  - FertilizationMethod
  - EmbryoFate
  - Description
  - EmbryoDescriptionID
  - KIDScore
  - KIDDate
  - KIDVersion
  - KIDUser
  
  # Time annotations (38 types)
  - BlastExpandLast
  - BlastomereSize
  - EVEN2
  - EVEN4
  - EVEN8
  - FRAG2
  - FRAG2CAT
  - FRAG4
  - FRAG8
  - Fragmentation
  - ICM
  - Line
  - MN2Type
  - MorphologicalGrade
  - MultiNucleation
  - Nuclei2
  - PN
  - Pulsing
  - ReexpansionCount
  - Strings
  - TE
  - t2
  - t3
  - t4
  - t5
  - t6
  - t7
  - t8
  - t9
  - tB
  - tEB
  - tHB
  - tM
  - tPB2
  - tPNa
  - tPNf
  - tSB
  - tSC
  
# IDAScore columns
idascore:
  - IDAScore
  - IDATime
  - IDAVersion
